services:
  - type: web
    name: esgi-donnesh
    runtime: node
    region: frankfurt
    repo: https://github.com/ZePoulet78/exoCloudNodeJS
    branch: main
    plan: free
    buildCommand: npm install
    startCommand: npm run start

databases:
  - name: exoCloudNodeJS
    region: frankfurt
    databaseName: mydb
    plan: free