services:
  - type: web
    name: esgi-donnesh
    runtime: node
    region: frankfurt
    branch: main
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: DB_URL
        fromDataBase:
          name: exoCloudNodeJS
          property: connectionString

databases:
  - name: exoCloudNodeJS
    region: frankfurt
    plan: free