services:
  - type: web
    name: esgi-donnesh
    runtime: node
    region: frankfurt
    repo: https://github.com/ZePoulet78/exoCloudNodeJS
    branch: main
    plan: free
    buildCommand: npm run build

databases:
  - name: exoCloudNodeJS
    databaseName: mydb
    user: donn
    plan: free